### ISSUE TITLE
Browserify compatibility

### ISSUE THREAD

**Issue by JustBlackBird** [noordawod/dom-ready#1]
Is there any chance the module will be compatible with [Browserify](browserify)?

**Comment by noordawod** [comment]
Hi @JustBlackBird.
I didn't think about that really... You're more than welcome to send a pull request for adding support, if you want.

**Comment by JustBlackBird** [comment]
Is the problem fixed now?

**Comment by noordawod** [comment]
It was not a problem. It was a request.

I don't know how to make the module compatible with Browserify and I'm currently busy with other projects. So like I mentioned before, if you'd like to contribute and submit a pull request to address this, please do.

**Comment by JustBlackBird** [comment]
Well, I've got your point. Could you please mark the issue with `won't fix` label to let others know that there is still no browserify compatibility?

**Comment by noordawod** [comment]
Definitely. Good idea. Thanks!
