### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by pyrsmk** [noordawod/dom-ready#3]
Hi,

I'm using your library for my framework. But it seems it doesn't work. The object is present in `window` but calling `domReady()` in `head` throw `Uncaught TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them`. And calling `domReady()` at the bottom of the page doesn't do nothing.

I'm using Opera 33 (Blink engine) on Windows 8.1

**Comment by noordawod** [comment]
@pyrsmk 

Thanks for reporting this issue. It's caused by using strict mode, as the error clearly states.

You have two options to fix this:

1) Remove "use strict" from your code.
2) Wait until I push a fix for it.

**Comment by noordawod** [comment]
@pyrsmk 

Are you using the latest source code? This was indeed a bug in previous versions, but has been resolved in latest version.

Try to use v1.0.4 which is the latest.

**Comment by pyrsmk** [comment]
It's the installed version ^^

**Comment by noordawod** [comment]
@pyrsmk 
I don't know what to tell you... I don't even see any `caller`, `callee` or `arguments` keyword at all.
Could you please copy-paste the exact stack trace for the error and in which line (in the code) this happens?

**Comment by pyrsmk** [comment]
It happens at line 96. And you're right, in the source on github that line doesn't exist anymore. But NPM installed me this version. The last publish command has probably fail. Or maybe NPM needs you to set a tag on the last commit with the right version (I know bower needs it).

**Comment by noordawod** [comment]
@pyrsmk I'm checking...

**Comment by noordawod** [comment]
@pyrsmk I made a new push just now, could you re-test and update?

**Comment by pyrsmk** [comment]
Great! The non-minified version works (but not the minified one).

**Comment by noordawod** [comment]
@pyrsmk Thanks for the update! I have now fixed also the minified version, so you should be alright. If you can check it out and approve that it's working, I'll be grateful.

**Comment by pyrsmk** [comment]
It works too ;)

**Comment by pyrsmk** [comment]
Thanks for your quick fix!

**Comment by noordawod** [comment]
You're welcome :)
